coverage:
  status:
    project:
      backend:
        flags:
          - backend
        target: auto
        threshold: 1%
        informational: true
      frontend:
        flags:
          - frontend
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true

github_checks:
  annotations: true

comment:
  layout: "reach,diff,flags,files"
  require_changes: false
