// Package openapicontract provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package openapicontract

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// HttpapiErrorResponse defines model for httpapi.errorResponse.
type HttpapiErrorResponse struct {
	Error string `json:"error"`
}

// HttpapiReadyResponse defines model for httpapi.readyResponse.
type HttpapiReadyResponse struct {
	Status    string `json:"status"`
	Timestamp string `json:"timestamp"`
}

// HttpapiStatusResponse defines model for httpapi.statusResponse.
type HttpapiStatusResponse struct {
	Status string `json:"status"`
}

// HttpapiUploadFileResponse defines model for httpapi.uploadFileResponse.
type HttpapiUploadFileResponse struct {
	ContentType string `json:"content_type"`
	FileId      string `json:"file_id"`
	FileName    string `json:"file_name"`
	SizeBytes   int    `json:"size_bytes"`
}

// PostUploadsAnimalPhotosMultipartBody defines parameters for PostUploadsAnimalPhotos.
type PostUploadsAnimalPhotosMultipartBody struct {
	// File Animal photo file to upload
	File openapi_types.File `json:"file"`
}

// PostUploadsAnimalPhotosMultipartRequestBody defines body for PostUploadsAnimalPhotos for multipart/form-data ContentType.
type PostUploadsAnimalPhotosMultipartRequestBody PostUploadsAnimalPhotosMultipartBody
