// Package openapicontract provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package openapicontract

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for HttpapiCreateAnimalRequestSpecies.
const (
	Cat  HttpapiCreateAnimalRequestSpecies = "cat"
	Dog  HttpapiCreateAnimalRequestSpecies = "dog"
	Goat HttpapiCreateAnimalRequestSpecies = "goat"
	Pig  HttpapiCreateAnimalRequestSpecies = "pig"
)

// HttpapiCreateAnimalRequest defines model for httpapi.createAnimalRequest.
type HttpapiCreateAnimalRequest struct {
	Birthdate *openapi_types.Date               `json:"birthdate,omitempty"`
	Name      string                            `json:"name"`
	PhotoId   *string                           `json:"photo_id,omitempty"`
	Species   HttpapiCreateAnimalRequestSpecies `json:"species"`
	Tag       *string                           `json:"tag,omitempty"`
}

// HttpapiCreateAnimalRequestSpecies defines model for HttpapiCreateAnimalRequest.Species.
type HttpapiCreateAnimalRequestSpecies string

// HttpapiCreateAnimalResponse defines model for httpapi.createAnimalResponse.
type HttpapiCreateAnimalResponse struct {
	AnimalId  string              `json:"animal_id"`
	Birthdate *openapi_types.Date `json:"birthdate,omitempty"`
	EventId   string              `json:"event_id"`
	Name      *string             `json:"name,omitempty"`
	PhotoId   *string             `json:"photo_id,omitempty"`
	Species   *string             `json:"species,omitempty"`
	Tag       *string             `json:"tag,omitempty"`
}

// HttpapiErrorResponse defines model for httpapi.errorResponse.
type HttpapiErrorResponse struct {
	Error string `json:"error"`
}

// HttpapiReadyResponse defines model for httpapi.readyResponse.
type HttpapiReadyResponse struct {
	Status    string `json:"status"`
	Timestamp string `json:"timestamp"`
}

// HttpapiStatusResponse defines model for httpapi.statusResponse.
type HttpapiStatusResponse struct {
	Status string `json:"status"`
}

// HttpapiUploadFileResponse defines model for httpapi.uploadFileResponse.
type HttpapiUploadFileResponse struct {
	ContentType string `json:"content_type"`
	FileId      string `json:"file_id"`
	FileName    string `json:"file_name"`
	SizeBytes   int    `json:"size_bytes"`
}

// PostAnimalsParams defines parameters for PostAnimals.
type PostAnimalsParams struct {
	// XRequestId Idempotency request key (omit to disable idempotency)
	XRequestId *string `json:"X-Request-Id,omitempty"`

	// XBarnlogSource Request source
	XBarnlogSource *string `json:"X-Barnlog-Source,omitempty"`
}

// PostUploadsAnimalPhotosMultipartBody defines parameters for PostUploadsAnimalPhotos.
type PostUploadsAnimalPhotosMultipartBody struct {
	// File Animal photo file to upload
	File openapi_types.File `json:"file"`
}

// PostAnimalsJSONRequestBody defines body for PostAnimals for application/json ContentType.
type PostAnimalsJSONRequestBody = HttpapiCreateAnimalRequest

// PostUploadsAnimalPhotosMultipartRequestBody defines body for PostUploadsAnimalPhotos for multipart/form-data ContentType.
type PostUploadsAnimalPhotosMultipartRequestBody PostUploadsAnimalPhotosMultipartBody
