// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createEvent = `-- name: CreateEvent :exec
INSERT INTO events (
    id,
    aggregate_type,
    aggregate_id,
    event_type,
    created_by,
    source,
    request_id,
    event_version,
    payload_json,
    metadata_json,
    occurred_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type CreateEventParams struct {
	ID            string         `json:"id"`
	AggregateType string         `json:"aggregate_type"`
	AggregateID   string         `json:"aggregate_id"`
	EventType     string         `json:"event_type"`
	CreatedBy     string         `json:"created_by"`
	Source        string         `json:"source"`
	RequestID     string         `json:"request_id"`
	EventVersion  int64          `json:"event_version"`
	PayloadJson   string         `json:"payload_json"`
	MetadataJson  sql.NullString `json:"metadata_json"`
	OccurredAt    string         `json:"occurred_at"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) error {
	_, err := q.db.ExecContext(ctx, createEvent,
		arg.ID,
		arg.AggregateType,
		arg.AggregateID,
		arg.EventType,
		arg.CreatedBy,
		arg.Source,
		arg.RequestID,
		arg.EventVersion,
		arg.PayloadJson,
		arg.MetadataJson,
		arg.OccurredAt,
	)
	return err
}
