// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
)

type Event struct {
	ID            string         `json:"id"`
	AggregateType string         `json:"aggregate_type"`
	AggregateID   string         `json:"aggregate_id"`
	EventType     string         `json:"event_type"`
	CreatedBy     string         `json:"created_by"`
	Source        string         `json:"source"`
	RequestID     string         `json:"request_id"`
	EventVersion  int64          `json:"event_version"`
	PayloadJson   string         `json:"payload_json"`
	MetadataJson  sql.NullString `json:"metadata_json"`
	OccurredAt    string         `json:"occurred_at"`
	CreatedAt     string         `json:"created_at"`
}
