// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag/v2"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "components": {
        "schemas": {
            "httpapi.errorResponse": {
                "properties": {
                    "error": {
                        "example": "invalid_json",
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "httpapi.readyResponse": {
                "properties": {
                    "status": {
                        "example": "ready",
                        "type": "string"
                    },
                    "timestamp": {
                        "example": "2026-02-22T20:32:13Z",
                        "format": "date-time",
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "httpapi.statusResponse": {
                "properties": {
                    "status": {
                        "example": "ok",
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "httpapi.uploadPhotoResponse": {
                "properties": {
                    "content_type": {
                        "example": "image/jpeg",
                        "type": "string"
                    },
                    "photo_id": {
                        "example": "photo_123",
                        "type": "string"
                    },
                    "size_bytes": {
                        "example": 248123,
                        "type": "integer"
                    }
                },
                "type": "object"
            }
        }
    },
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "version": "{{.Version}}"
    },
    "externalDocs": {
        "description": "",
        "url": ""
    },
    "paths": {
        "/healthz": {
            "get": {
                "description": "Returns service liveness status.",
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/httpapi.statusResponse"
                                }
                            }
                        },
                        "description": "OK"
                    }
                },
                "summary": "Health check",
                "tags": [
                    "system"
                ]
            }
        },
        "/readyz": {
            "get": {
                "description": "Returns service readiness status and current UTC timestamp.",
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/httpapi.readyResponse"
                                }
                            }
                        },
                        "description": "OK"
                    }
                },
                "summary": "Readiness check",
                "tags": [
                    "system"
                ]
            }
        },
        "/uploads/photos": {
            "post": {
                "description": "Uploads a photo file and returns a generated photo_id.",
                "requestBody": {
                    "content": {
                        "application/x-www-form-urlencoded": {
                            "schema": {
                                "title": "photo",
                                "type": "file"
                            }
                        },
                        "multipart/form-data": {
                            "schema": {
                                "type": "object"
                            }
                        }
                    },
                    "description": "Photo file",
                    "required": true
                },
                "responses": {
                    "201": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/httpapi.uploadPhotoResponse"
                                }
                            }
                        },
                        "description": "Created"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/httpapi.errorResponse"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "413": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/httpapi.errorResponse"
                                }
                            }
                        },
                        "description": "Request Entity Too Large"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/httpapi.errorResponse"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "Upload photo",
                "tags": [
                    "uploads"
                ]
            }
        }
    },
    "openapi": "3.1.0",
    "servers": [
        {
            "url": "http://localhost:8080"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Title:            "Barnlog Backend API",
	Description:      "Barnlog backend HTTP API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
